"""
archery_parser — Ianseo PDF qualification result → structured CSV pipeline.

Converts archery competition result PDFs generated by the Ianseo competition
management system into structured, arithmetically-verified CSV files suitable
for database import and statistical analysis.

Typical usage via CLI:
    python -m archery_parser input.pdf --output results.csv

Pipeline stages:
    1. reader      — PDF → raw words with (x,y) coordinates
    2. detector    — raw words → CompetitionMeta + list[RawSection]
    3. assembler   — RawSection list → list[AthleteRecord]
    4. transformer — AthleteRecord list → list[CSVRow]
    5. writer      — CSVRow list → verified CSV file on disk
"""

__version__ = "1.0.0"
